name = "RetirementPlanners"
uuid = "2683bf95-d0b8-4c71-a7d3-b42f78bf1cf0"
authors = ["itsdfish"]
version = "0.1.0"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
